### ISSUE TITLE
travis build faild

### ISSUE THREAD

**Issue by Jayin** [docpress/docpress#17]
First of all , I copy [following string](https://github.com/docpress/docpress/blob/master/docs%2Fadvanced%2Fgh-pages.md) into my `.travis.yml` but build faild (the project is not  a Node.js project)
```yml
# .travis.yml
node_js:
- 4

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: rstacruz/myproject
    - GIT_SOURCE: _docpress

script:
- rake     # ...or whatever your test command is
- npm install docpress && ./node_modules/.bin/docpress build

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi
```

Then build faild with following error:

```shell
Setting environment variables from repository settings
$ export GITHUB_TOKEN=[secure]
Setting environment variables from .travis.yml
$ export GIT_NAME=Travis
$ export GIT_EMAIL=nobody@nobody.org
$ export GITHUB_REPO=rstacruz/myproject
$ export GIT_SOURCE=_docpress
0.00s
rvm
0.11s$ rvm use default
Using /home/travis/.rvm/gems/ruby-1.9.3-p551
$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.4.5
50.61s$ npm install docpress && ./node_modules/.bin/docpress build
----\npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
-/-\/npm WARN optional dep failed, continuing fsevents@1.0.6
-----/--\||/-npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
---/---\\\|\-\\\||//-\\\\|/|\\\\npm WARN engine postcss@5.0.12: wanted: {"node":">=0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
/|/-\\/\---/-|--|---|/\|/--\---\---docpress@0.6.10 node_modules/docpress
├── yargs@3.30.0 (camelcase@1.2.1, window-size@0.1.4, y18n@3.2.0, decamelize@1.1.2, os-locale@1.4.0, cliui@3.1.0)
├── docpress-search@0.6.0 (ware@1.3.0, uglifyify@3.0.1, lunr@0.5.12, browserify@11.2.0)
├── metalsmith-start@1.4.2 (object-assign@3.0.0, get-port@1.0.0, thunkify@2.1.2, co@4.6.0, debounce-collect@1.0.2, connect-livereload@0.5.3, unyield@0.0.1, commander@2.9.0, chalk@1.1.1, mz@2.1.0, connect@3.4.0, chokidar@1.2.0, tiny-lr@0.2.1, gnode@0.1.1, observatory@1.0.0, superstatic@3.0.0, metalsmith@2.1.0)
├── docpress-base@0.6.10 (github-markdown-css@2.1.1, normalize.css@3.0.3, nprogress@0.2.0, pjax@0.1.4, onmount@1.1.0, debounce@1.0.0, ware@1.3.0, dom101@1.2.0, iconfonts@0.8.0, stylus@0.52.4, postcss@5.0.12, jade@1.11.0, uglifyify@3.0.1, browserify@12.0.1, autoprefixer@6.1.2)
└── docpress-core@0.6.0 (slugify@0.1.1, markdown-it-decorate@1.0.0, marked@0.3.5, debug@2.2.0, ware@1.3.0, cheerio@0.19.0, markdown-it@5.0.0, highlight.js@8.8.0, metalsmith@2.1.0, lodash@3.10.1)
/home/travis/build/EManual/docs/node_modules/docpress/bin/docpress:15
    docpress(cwd).build((err, res) => {
                                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
The command "npm install docpress && ./node_modules/.bin/docpress build" exited with 8.
Done. Your build exited with 1.
```

And once I add `language: node_js`  in head of  `.travis.yml`  and it works.
So the document should add specify `language` in `.travis.yml`  ?
