### ISSUE TITLE
watch mode in docker doesn't reload page

### ISSUE THREAD

**Issue by airtonix** [docpress/docpress#239]
It's be great if watch mode in docker would work.

to make this happen, you need to allow setting the live-reload port from docpress, [otherwise `get-port` will choose a random port every time](https://github.com/rstacruz/metalsmith-start/blob/master/lib/runner.js#L143-L144), which isn't feasible for docker-compose.

```
version: "2.1"

services:

  frontend:
    image: my-image-name
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    working_dir: /opt/app/
    command: npm run serve
    volumes:
      - ./package.json:/opt/app/package.json
      - ./docs:/opt/app/docs
      - ./README.md:/opt/app/README.md
      - /opt/app/node_modules
```
